<?php

namespace QF\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends EntityRepository
{
}
