<?php

namespace Quantifier\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * binariesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class binariesRepository extends EntityRepository
{
}
