<?php

namespace Quantifier\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvolutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolutionRepository extends EntityRepository
{
}
