<?php

namespace Quantifier\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProportionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProportionRepository extends EntityRepository
{
}
